README.md
Hi you’ve got an extra backtick there! I actually need this project right now and it’s perfect. Keep at it 👍
=> typo: remove extra backtick

cli/src/binaries/mod.rs, cli/src/prisma_cli.rs
=> fix: fixed usage of Prisma binaries

Cargo.lock, Cargo.toml, README.md, cli/src/binaries/mod.rs, cli/src/binaries/platform.rs, cli/src/generator/ast/dmmf.rs
Engine binary targets retrieved from https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#binarytargets-options
=> arm64 & Prisma 3.13.0 support

cli/src/generator/models.rs, integration-tests/tests/count.rs, integration-tests/tests/lib.rs, src/queries/count.rs, src/queries/mod.rs
=> Record count query

examples/with-actix/.env.example, examples/with-actix/Cargo.toml, examples/with-actix/README.md, examples/with-actix/prisma/schema.prisma, examples/with-actix/src/main.rs
=> feat: add actix web example

examples/rocket/Cargo.toml, examples/rocket/README.md, examples/rocket/Rocket.toml, examples/rocket/prisma/schema.prisma, examples/rocket/src/main.rs
Hello again, feel free to close if you don't want this but I yoinked the guts from the Axum example I wrote to put together this barebones example using [Rocket](https://rocket.rs/) for #38
=> added rocket example

docs/02-setup.md
+thanks for your work on this project!
=> fix typo in setup instructions

src/queries/batch.rs
Tiny clean-up of batch output.
=> Remove unconditional dbg! from batch.rs

src/queries/upsert.rs
=> use IncludeType in Upsert::include

cli/src/generator/enums.rs, cli/src/generator/internal_enums.rs
=> impl PartialEq and Eq for enums

cli/src/generator/models/mod.rs, cli/src/generator/models/set_params.rs, cli/src/generator/read_filters.rs, sdk/src/args.rs, sdk/src/extensions.rs, sdk/src/keywords.rs, sdk/src/utils.rs
=> make not function optional for optional fields

cli/src/generator/client.rs, integration-tests/tests/batch.rs, src/queries/batch.rs, src/queries/count.rs, src/queries/create.rs, src/queries/create_many.rs, src/queries/delete.rs, src/queries/delete_many.rs, src/queries/execute_raw.rs, src/queries/find_first.rs, src/queries/find_many.rs, src/queries/find_unique.rs, src/queries/include.rs, src/queries/mod.rs, src/queries/query.rs, src/queries/query_raw.rs, src/queries/select.rs, src/queries/update.rs, src/queries/update_many.rs, src/queries/upsert.rs
=> Mixed batch containers

examples/actix/src/main.rs, examples/axum-rest/src/main.rs, examples/rspc/src/main.rs
=> Minor fixes

sdk/src/args.rs, tests/database/postgres/prisma/schema.prisma
=> Unify read filter retrieval logic

crates/cli/src/generator/models/include_select.rs
Conflicting issues when fixing custom results
=> Conflicting issues when fixing custom results

docs/pages/reading-data/order-by.md
Noticed a small documentation error while I was working, tiny PR for the fix.
=> Documentation Error for Order By

crates/cli/src/generator/models/data.rs, crates/cli/src/generator/models/include_select.rs, crates/cli/src/generator/models/mod.rs
Dedicated `Type` aliases for each field module
=> Field types

crates/cli/src/generator/composite_types/order_by.rs, crates/cli/src/generator/composite_types/set_params.rs, crates/cli/src/generator/composite_types/where_params.rs, crates/cli/src/generator/models/create.rs, crates/cli/src/generator/models/order_by.rs, crates/cli/src/generator/models/set_params.rs, crates/cli/src/generator/models/types.rs, crates/cli/src/generator/models/where_params.rs, crates/cli/src/generator/models/with_params.rs, crates/cli/src/generator/read_filters.rs, crates/cli/src/generator/write_params.rs, crates/lib/src/queries/find_many.rs, crates/lib/src/queries/find_unique.rs
To help with debugging in userspace.
=> Debug on types

crates/generator/src/models/filter.rs, crates/generator/src/models/include_select.rs, crates/generator/src/models/mod.rs, crates/generator/src/models/partial_unchecked.rs, crates/macros/src/filter.rs, crates/macros/src/lib.rs, integration-tests/schema.prisma, integration-tests/tests/find_many.rs
=> filter! macro

docs/pages/reading-data/fetch.md
Just a simple typo fix
`prisam` -> `prisma`
=> Update fetch.md - fix typo

src/raw.rs
Support for both string or number for decimal.
=> fix(RawPrismaValue): decimal string matching

crates/cli/src/binaries/mod.rs
This renames the tmp file to the final location instead of copying it. It would previously leave around a temp file. Not a huge deal, but when doing this in a docker container, it adds almost 200MB to the final image that otherwise needs to be cleaned up in a sort of hacky way
=> Don't leave tmp file when download libs
