Brendonovich/prisma-client-rust

- cli/src/generator/codegen/client.rs
This allows to derive debug for structs that contain PrismaClient
> Add dummy debug implementation for PrismaClient

- examples/axum/Cargo.toml
- examples/axum/README.md
- examples/axum/prisma/schema.prisma
- examples/axum/src/main.rs
- examples/axum/src/routes.rs
The repo only has an example with axum combined with GraphQL.
I think it would be great to also have a more classic REST API example, so here is my proposal.
And as an added bonus it shows a way to handle Prisma errors with a centralized error handler.
> Adds an example with a REST API Axum backend

- Cargo.toml
- cli/Cargo.toml
- sdk/Cargo.toml
Adds a specification for the Minimum Supported Rust Version (MSRV).
`#[derive(Default)]` on enums with a `#[default]` was added to the rust stable channel in version 1.62. 
see: 
https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
https://github.com/rust-lang/rust/pull/94457
> fix: specify minimum rust version

- cli/src/generator/models/data.rs
- cli/src/generator/models/include.rs
- cli/src/generator/models/select.rs
- docs/src/pages/extra/rspc.md
- docs/src/pages/getting-started/installation.md
- docs/src/pages/getting-started/setup.md
- docs/src/pages/reading-data/select-include.md
- examples/rspc/bindings.ts
- examples/rspc/src/main.rs
Changes how rspc types are generated, with relations not being included in model types, favouring use of `include` over `with`/`fetch`.
> Better rspc integration

- src/queries/create_many.rs
According to the hard-coded capabilities, the following two DB do not support skip_duplicates:
- mssql
- MongoDB
Therefore, remove skip_duplicates field whenever one of these two features is enabled.
> fix "Argument skipDuplicates Does Not Exist On Enclosing Type" in create_many

- cli/src/generator/models/actions.rs
- integration-tests/tests/count.rs
The `_where` param was unused, as described in https://github.com/Brendonovich/prisma-client-rust/issues/177
> fix: use where parms in count generated code

- cli/src/generator/models/mod.rs
- src/lib.rs
- src/operator.rs
- src/queries/count.rs
- src/queries/create.rs
- src/queries/create_many.rs
- src/queries/delete_many.rs
- src/queries/find_first.rs
- src/queries/find_many.rs
- src/queries/update.rs
- src/queries/update_many.rs
Wraps fields of the `and` operator in `merge_fields` in the same way as regular objects.
Closes #175
> merge and operator fields

- sdk/src/binaries/platform.rs
On a fresh Fedora Workstation 37 install, the `openssl` binary is not installed. This lead to an unhelpful error message when trying to run `cargo prisma`:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
Os { code: 2, kind: NotFound, message: "No such file or directory" }',
/home/aiden/.cargo/git/checkouts/prisma-client-rust-fa967aa5ad0ec391/e12e693/sdk/src/binaries/platform.rs:116:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
The backtrace eventually lead me to the source to determine the issue.
> Improve error message when `openssl version -v` fails

- examples/axum-rest/Cargo.toml
- examples/axum-rest/src/main.rs
- examples/axum-rest/src/routes.rs
The `axum-rest` example couldn't be run with `cargo run`, so I enabled the `mocking` feature to fix it. 
I also fixed some comments and made the imports consistent.
> Update axum-rest example 

- crates/cli/src/binaries/platform.rs
Found out that due to Arch Linux updating to OpenSSL 3.1.*, it broke `pnpm prep` at Spacedrive, it was trying to fetch a version that doesn't exist of bundled OpenSSL from the Prisma team. Now using 3.0.x version as it is API compatible.
> Handling prisma not having a OpenSSL bundle for version 3.1.x

- docs/pages/extra/error-handling.md
Fixed a minor typo in a code snippet at https://prisma.brendonovich.dev/extra/error-handling.
> Fix minor typo in error handling docs page

- crates/generator/src/models/actions.rs
- crates/generator/src/models/set_params.rs
- crates/generator/src/models/types.rs
- crates/generator/src/models/where_params.rs
- crates/lib/src/queries/count.rs
- crates/lib/src/queries/delete.rs
- crates/lib/src/queries/find_first.rs
- crates/lib/src/queries/find_many.rs
- crates/lib/src/queries/find_unique.rs
- crates/lib/src/queries/query.rs
- crates/lib/src/queries/update.rs
- crates/lib/src/queries/update_unchecked.rs
- crates/lib/src/queries/upsert.rs
Compound unique fields are being included in `WhereParam` which isn't good since they should actually only be available in `UniqueWhereParam`.
> Restrict compound uniques to unique params

- crates/generator/src/header.rs
Make the missing migrations dir error message more helpful.
I was originally going to change the function to actually create the missing folder (can still do this if you want).
> Update migrations error message

- crates/cli/src/binaries/mod.rs
- crates/cli/src/prisma_cli.rs
- integration-tests/tests/lib.rs
Closes #395
It adds support for operating systems that Prisma does not compile binaries for like NixOS by setting the needed env variables for the engines.
It should still support the previous way of working but it's worth noting that I haven't tested that yet.
I currently only have a NixOS machine so I haven't been able to test it on something like Darwin.
> Feature: Allow skipping downloads of engines by setting env vars

- Cargo.lock
- crates/lib/Cargo.toml
- crates/lib/src/client.rs
- examples/axum-graphql/Cargo.toml
The `dotenv` crate has been unmaintained since 2020. 
The `dotenvy` crate is a fork of `dotenv`, is actively maintained, and provides the same functionality.
See this GitHub issue: https://github.com/dotenv-rs/dotenv/issues/74
This resolves RUSTSEC-2021-0141
> Replace dotenv with dotenvy

- Cargo.lock
- crates/lib/Cargo.toml
- crates/lib/src/migrations.rs
The `tempdir` crate has been unmaintained since 2018, and has known vulnerabilities. This PR replaces it with `tempfile`, which provides the same functionality, and is actively maintained.
Resolves:
1. RUSTSEC-2023-0018
2. RUSTSEC-2018-0017
> Replace tempdir dependency with tempfile

- Cargo.lock
- Cargo.toml
Okay this time we actually need it.
`0.2.0` doesn't have typesafe error handling so we can't just drop the integration, yet.
> rspc 0.2.0

- crates/lib/src/client.rs
This is helpful when it tells you the unwrap errors in the changed line, to instead make sure the user knows what's wrong instead of having to dive through the library's code!
> Add helpful error message whenever datasource cannot be fetched

- crates/generator/src/read_filters.rs
- crates/sdk/src/extensions.rs
https://discord.com/channels/1011665225809924136/1011666506083487775/1305292266386227210
> fix generated JsonFilter type mismatch

- crates/generator/src/models/set_params.rs
- crates/generator/src/models/where_params.rs
The impl keyword in the generator crate was incorrectly capitalized in some places, causing a Rust compilation error in the generated client code
> fix: wrong case for impl keyword in models/set_params and models/where_params
